data:
  name: pl
  path: ./data/crossdocked_v1.1_rmsd1.0_pocket10
  split: ./data/crossdocked_pocket10_pose_split.pt
  transform:
    ligand_atom_mode: add_aromatic
    random_rot: False

model:
  model_mean_type: C0  # ['noise', 'C0']
  beta_schedule: sigmoid
  beta_start: 1.e-7
  beta_end: 2.e-3
  v_beta_schedule: cosine
  v_beta_s: 0.01
  num_diffusion_timesteps: 1000
  loss_v_weight: 100.
  sample_time_method: symmetric  # ['importance', 'symmetric']

  time_emb_dim: 0
  time_emb_mode: simple
  center_pos_mode: protein

  node_indicator: True
  model_type: graphormer
  num_layers: 3
  n_heads: 8
  hidden_dim: 128
  dropout_rate: 0.1
  input_dropout_rate: 0.1
  weight_decay: 0.01
  ffn_dim: 512
  warmup_updates: 1000
  tot_updates: 10000
  peak_lr: 0.001
  end_lr: 0.0001
  edge_type: 'bond'
  multi_hop_max_dist: 3
  attention_dropout_rate: 0.2
  flag: true
  flag_m: 0.1
  flag_step_size: 0.01
  flag_mag: 0.5

train:
  seed: 2021
  batch_size: 1
  num_workers: 4
  n_acc_batch: 1
  max_iters: 10000000
  val_freq: 100
  pos_noise_std: 0.1
  max_grad_norm: 8.0
  bond_loss_weight: 1.0
  optimizer:
    type: adam
    lr: 5.e-4
    weight_decay: 0
    beta1: 0.95
    beta2: 0.999
  scheduler:
    type: plateau
    factor: 0.6
    patience: 10
    min_lr: 1.e-6
